// Generated by CoffeeScript 1.6.3
Application.popup = (function() {
  function popup() {
    this.selector = "#cards";
  }

  popup.prototype.createCardsList = function(cards, projectName) {
    var card, html, _i, _len, _results, _selector;
    console.log(this.selector);
    _selector = $("" + this.selector);
    _selector.append("<li><h5>" + projectName + "</h5></li>");
    _results = [];
    for (_i = 0, _len = cards.length; _i < _len; _i++) {
      card = cards[_i];
      console.log(card);
      html = "<li>" + card.name + " [#" + card.id + "]</li>";
      _results.push(_selector.append(html));
    }
    return _results;
  };

  return popup;

})();

$(function() {
  var pv;
  pv = new PivotalTracker();
  return pv.retreiveCards();
});
