// Generated by CoffeeScript 1.6.3
var Options,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

Options = {};

Options = (function() {
  function Options() {
    this.apiToken = localStorage['apiToken'];
    if ((localStorage['projects'] != null) && localStorage['projects'] !== "") {
      this.projects = JSON.parse(localStorage['projects']);
    } else {
      this.projects = [];
    }
  }

  Options.prototype.triggerApiTokenChanges = function() {
    var _this = this;
    return $("#apiToken").on("change", function(e) {
      _this.apiToken = $(e.currentTarget).val();
      localStorage['apiToken'] = _this.apiToken;
      localStorage['projects'] = [];
      _this.findProjects();
      return true;
    });
  };

  Options.prototype.triggerProjectChanges = function() {
    return $(function() {
      return $(document).on("click", ".project", function(e) {
        var checked, values, _i, _len, _ref;
        values = [];
        _ref = $(".project:checked");
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          checked = _ref[_i];
          values.push({
            name: $(checked).data("name"),
            id: $(checked).val()
          });
        }
        localStorage['projects'] = JSON.stringify(values);
        return console.log(localStorage['projects']);
      });
    });
  };

  Options.prototype.fillOptionsPage = function() {
    return $("#apiToken").val(this.apiToken);
  };

  Options.prototype.findProjects = function() {
    var projectsUrl, setHeader,
      _this = this;
    projectsUrl = "https://www.pivotaltracker.com/services/v5/projects";
    setHeader = function(xhr) {
      console.log(_this.apiToken);
      return xhr.setRequestHeader('X-TrackerToken', "" + _this.apiToken);
    };
    return $.ajax({
      url: projectsUrl,
      type: "GET",
      dataType: "json",
      success: function(data) {
        return _this.fillProjectsList(data);
      },
      error: function() {
        return alert("Sorry an error has occured");
      },
      beforeSend: setHeader
    });
  };

  Options.prototype.fillProjectsList = function(projects) {
    var checked, html, project, _i, _len, _ref, _results, _selector;
    _selector = $("#projects");
    _selector.html("");
    _results = [];
    for (_i = 0, _len = projects.length; _i < _len; _i++) {
      project = projects[_i];
      checked = "";
      if (_ref = "" + project.id, __indexOf.call(this.projects.map(function(p) {
        return p.id;
      }), _ref) >= 0) {
        checked = "checked";
      }
      html = "<li><input type='checkbox' value='" + project.id + "' class='project' " + checked + " data-name='" + project.name + "'/>" + project.name + "</li>";
      _results.push(_selector.append(html));
    }
    return _results;
  };

  return Options;

})();
