// Generated by CoffeeScript 1.6.3
$(function() {
  var options;
  options = new Options;
  options.fillOptionsPage();
  options.triggerApiTokenChanges();
  options.triggerProjectChanges();
  if (options.apiToken != null) {
    return options.findProjects();
  }
});
