// Generated by CoffeeScript 1.6.3
var PivotalTracker;

PivotalTracker = (function() {
  function PivotalTracker() {
    this.options = new Options;
  }

  PivotalTracker.prototype.retreiveCards = function() {
    var popup, project, projectName, setHeader, _i, _len, _ref, _results,
      _this = this;
    setHeader = function(xhr) {
      return xhr.setRequestHeader('X-TrackerToken', "" + _this.options.apiToken);
    };
    popup = new Application.popup();
    console.log(this.options.projects);
    _ref = this.options.projects;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      project = _ref[_i];
      projectName = project.name;
      _results.push($.ajax({
        url: "https://www.pivotaltracker.com/services/v5/projects/" + project.id + "/stories?date_format=millis&with_state=started",
        type: "GET",
        dataType: "json",
        success: function(data) {
          return popup.createCardsList(data, projectName);
        },
        error: function() {
          return alert("Sorry an error has occured");
        },
        beforeSend: setHeader
      }));
    }
    return _results;
  };

  return PivotalTracker;

})();
